<a href="https://colab.research.google.com/github/GouravNayak/Python--Order_Scheduling_Optimization/blob/main/Order_scheduling_optimizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**import libraries**

In [ ]:
import pandas as pd
import numpy as np

**Read the excel**

In [ ]:
df = pd.read_excel(r'/content/Test_1.xlsx', index_col=0)
print(df.head())
sku_list = list(df.index.values)
df_col = df.shape[1]

   A  B  C  D
1  1  0  1  2
2  1  1  0  2
3  2  0  1  0
4  0  1  2  3
5  3  1  0  1


**Function to check shared order**

In [ ]:
def get_jaccard_coefficent(input_sku_1, input_sku_2):
  # print('finding coefficent for '+ str(input_sku_1) + ', ' + str(input_sku_2))
  data = [df.loc[input_sku_1], df.loc[input_sku_2]]
  temp_sku = pd.concat(data, axis=1)
  
  jaccard_coefficent_num = 0
  jaccard_coefficent_den = temp_sku.sum(axis=0, skipna=True).loc[input_sku_1] + temp_sku.sum(axis=0, skipna=True).loc[input_sku_2]
  shared_order_var = 0
  for index, row in temp_sku.iterrows():
    num_1 = temp_sku[input_sku_1][index]
    num_2 = temp_sku[input_sku_2][index]
    if num_1>0 and num_2>0:
      shared_order_var = min(num_1, num_2)
    else:
      shared_order_var = 0
    jaccard_coefficent_num = jaccard_coefficent_num+shared_order_var
  jaccard_coefficent = jaccard_coefficent_num/jaccard_coefficent_den
  
  return jaccard_coefficent

**Create a numpy array**

In [ ]:
result_array = np.zeros((len(sku_list),len(sku_list)),dtype=float)

In [ ]:
row_count = 0
for sku_row in sku_list:
  #print('processing row: ',row_count)
  col_count = 0
  for sku_col in sku_list:
    #print('processing col: ',col_count)
    if sku_row==sku_col:
      result_array[row_count][col_count] = 0
    else:
      result_array[row_count][col_count] = get_jaccard_coefficent(sku_row, sku_col)
    col_count = col_count+1
  row_count = row_count+1
print(result_array)

[[0.         0.375      0.28571429 0.3        0.22222222]
 [0.375      0.         0.14285714 0.3        0.33333333]
 [0.28571429 0.14285714 0.         0.11111111 0.25      ]
 [0.3        0.3        0.11111111 0.         0.18181818]
 [0.22222222 0.33333333 0.25       0.18181818 0.        ]]
